apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deploy
spec:
  template:
    spec:
      containers:
      - name: simpleapp
        resources:
        limits:
          memory: 512Mi