# run with busybox to view nginx
# kubectl port-forward -n default pod/nginx-deployment-7dbc5548c4-rjqpn  5555:80    
# http://localhost:8001/api/v1/namespaces/default/services/nginx-svc:80/proxy/
# https://gardener.cloud/050-tutorials/content/howto/access_pod_from_local/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-svc
  namespace: default
spec:
  type: ClusterIP  
  ports:
    - port: 80
  selector:
    app: nginx-app