# docker-compose build
# docker-compose up -d
# docker-compose ps
# docker-compose logs -f app
# docker-compose down --volumes

version: '3.7'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db-net
    volumes: 
      - my-db:/var/lib/mysql
  app:
    build: 
      context: .
      dockerfile: dockerize.DockerFile
    ports:
      - 3000:3000
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - db-net
volumes:
  my-db:
networks:
  db-net:
    driver: bridge