apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx-app
  labels:
    app: simpleapp
    env: development
spec:
  containers:
  - name: nginx-app
    image: nginx
    ports:
    - containerPort: 80