# kg secret

apiVersion: v1
kind: Pod
metadata:
  name: simpleapp-ch4-mount
  labels:
    app: simpleapp-ch4
    env: development
spec:
  volumes:
  - name: vol-secret
    secret:
      secretName: cats-and-dogs
  containers:
  - name: simpleapp
    image: howtoautomateinth/docker-simpleapp:v1.1
    ports:
      - containerPort: 5000
    volumeMounts:
    - name: vol-secret
      mountPath: /etc/app/secrets